## CI variables:
# - BACKUP_INSTANCE
# - GCLOUD_SERVICE_ACCOUNT_KEY
# - MYSQL_USER
# - MYSQL_PASSWORD

image: loicmahieu/mysql-xtrabackup:v1.3.0

backup:
  script:
    - GCLOUD_BUCKET=gs://bucket

    - '[ "$BACKUP_INSTANCE" = "" ]
        && echo "Could not find variable BACKUP_INSTANCE."
        && exit 1'

    - TEMP_DIR=/tmp/backup
    - mkdir -p $TEMP_DIR

    - xtrabackup-runner prepareAuto
      --gcloudBackupPath=$GCLOUD_BUCKET/$BACKUP_INSTANCE/backup/
      --gcloudTargetPath=$GCLOUD_BUCKET/$BACKUP_INSTANCE/prepared/

    - xtrabackup-runner clean
      --gcloudBackupPath=$GCLOUD_BUCKET/$BACKUP_INSTANCE/prepared/
      --backupMaxAge=30
